[project]
name = "mcpbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "mcp[cli]>=1.9.1",
    "ollama>=0.4.8",
    "requests>=2.32.3",
    "uvicorn>=0.34.2",
]
